package tpi.dgrv4.entity.constant;

public enum TsmpSequenceName {
	SEQ_TSMP_GROUP_PK,
	SEQ_TSMP_VGROUP_PK,
	SEQ_TSMP_TOKEN_HISTORY_PK,
	SEQ_TSMP_CLIENT_HOST_PK,
	SEQ_TSMP_USER_PK,
	SEQ_TSMP_ROLE_PK,
	SEQ_TSMP_ORGANIZATION_PK,
	SEQ_TSMP_REG_HOST_PK,
	SEQ_TSMP_DC_PK,
	SEQ_TSMP_ALERT_PK,
	SEQ_TSMP_API_DETAIL_PK,
	SEQ_TSMP_API_MODULE_PK,
	SEQ_TSMPN_API_DETAIL_PK,
	SEQ_TSMPN_API_MODULE_PK,
	SEQ_TSMP_NODE_TASK_PK
	;
}
